require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|

  config.vm.box       = 'openstack'
  config.ssh.username = 'stack'

  config.vm.provider :openstack do |os|
    os.openstack_auth_url = 'http://192.168.103.191:5000/v2.0'
    os.username           = 'bsv'
    os.password           = '1q2w3e'
    os.tenant_name        = 'BSV'
    os.flavor             = 'm1.small'
    os.image              = 'CentOS-6-GenericCloud-1508'
#    os.floating_ip_pool   = 'public'
#    os.networks           = ['net1','net2']
  end
end
